import {
  Sparkles,
  Users,
  Briefcase,
  Settings,
  Building,
  Zap,
} from "lucide-react";

export const INITIAL_PITCHES = [
  {
    id: "pitch-1",
    type: "Talent Showcase",
    typeBadge: "TALENT",
    expiresIn: "Expires in 24h 40m",
    headline: "«Turning complex workflows into simple, high-converting digital products»",
    description:
      "I help high-growth startups and fintechs turn complex technical architecture into effortless, intuitive user interfaces that accelerate conversion and customer retention.",
    skills: ["UI/UX", "Figma", "UX Research", "UI Design", "Product Strategy"],
    category: "Talents",
    cta: "Hire Me",
    creator: {
      name: "Osakwe Prisca",
      role: "Senior Product Designer",
      location: "Lagos, Nigeria (Remote)",
      availability: "Available Immediately",
      image: "/assets/images/prisca.png",
      verified: true,
    },
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    videoPoster: "",
    likes: 124,
    shares: 42,
    views: 890,
    ctaCount: 24,
    isLiked: false,
    duration: "0:30",
  },
  {
    id: "pitch-2",
    type: "Skill Showcase",
    typeBadge: "SKILL",
    expiresIn: "Expires in 22h 15m",
    headline: "«Architecting resilient cloud systems & high-throughput APIs that scale to millions»",
    description:
      "Senior Full-Stack Engineer with 6+ years specializing in distributed systems, high-concurrency microservices, and slick React frontends.",
    skills: ["React", "Node.js", "TypeScript", "PostgreSQL", "AWS", "Docker"],
    category: "Talents",
    cta: "Hire Me",
    creator: {
      name: "David Adeleke",
      role: "Lead Fullstack Engineer",
      location: "Abuja, Nigeria (Hybrid)",
      availability: "Available Immediately",
      image: "/assets/images/photo_placeholder.png",
      verified: true,
    },
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    videoPoster: "",
    likes: 89,
    shares: 19,
    views: 520,
    ctaCount: 14,
    isLiked: false,
    duration: "0:45",
  },
  {
    id: "pitch-3",
    type: "Hiring Opportunity",
    typeBadge: "HIRING",
    expiresIn: "Expires in 23h 05m",
    headline: "«We are hiring Senior Product Managers to lead our fintech expansion across Africa»",
    description:
      "Bejite is looking for visionary leaders passionate about digital talent ecosystems, cross-border payments, and empowering modern builders.",
    skills: ["Product Roadmap", "Growth", "Fintech", "User Research", "Agile"],
    category: "Hiring",
    cta: "Apply Now",
    creator: {
      name: "Bejite Careers",
      role: "Talent Acquisition",
      location: "Global Remote",
      availability: "3 Positions Open",
      image: "/assets/images/logo.png",
      verified: true,
    },
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
    videoPoster: "",
    likes: 215,
    shares: 68,
    views: 1420,
    ctaCount: 52,
    isLiked: false,
    duration: "0:50",
  },
  {
    id: "pitch-4",
    type: "Service Pitch",
    typeBadge: "SERVICE",
    expiresIn: "Expires in 19h 30m",
    headline: "«High-velocity brand identity and design sprints for venture-backed seed startups»",
    description:
      "We build iconic visual identities, investor pitch decks, and digital design systems that make enterprise-grade first impressions.",
    skills: ["Branding", "Design Systems", "Webflow", "Pitch Decks", "Motion"],
    category: "Services",
    cta: "Book Intro Call",
    creator: {
      name: "Studio Apex",
      role: "Creative Agency",
      location: "Lagos & London",
      availability: "Accepting Q3 Projects",
      image: "/assets/images/photo_placeholder.png",
      verified: true,
    },
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4",
    videoPoster: "",
    likes: 156,
    shares: 31,
    views: 680,
    ctaCount: 18,
    isLiked: false,
    duration: "0:35",
  },
  {
    id: "pitch-5",
    type: "Skill Showcase",
    typeBadge: "SKILL",
    expiresIn: "Expires in 18h 45m",
    headline: "«Machine Learning & Data Engineering for high-volume fraud detection and risk models»",
    description:
      "Data Scientist with 5 years experience creating production-grade anomaly detection pipelines, NLP models, and real-time inference microservices.",
    skills: ["Python", "PyTorch", "Kafka", "FastAPI", "Docker", "MLOps"],
    category: "Talents",
    cta: "Hire Me",
    creator: {
      name: "Zainab Mohammed",
      role: "Lead Machine Learning Engineer",
      location: "Kano, Nigeria (Remote)",
      availability: "Available Next Month",
      image: "/assets/images/photo_placeholder.png",
      verified: true,
    },
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
    videoPoster: "",
    likes: 178,
    shares: 45,
    views: 940,
    ctaCount: 32,
    isLiked: false,
    duration: "0:40",
  },
  {
    id: "pitch-6",
    type: "Work Showcase",
    typeBadge: "WORK",
    expiresIn: "Expires in 21h 10m",
    headline: "«How we grew our B2B SaaS platform from zero to 20,000 paid active subscribers in 9 months»",
    description:
      "A 40-second teardown of our product-led onboarding funnel, viral referral loops, and behavioral email triggers that tripled user activation.",
    skills: ["Growth Marketing", "B2B SaaS", "Funnel Optimization", "Analytics"],
    category: "Services",
    cta: "View Case Study",
    creator: {
      name: "Tobi Amusan",
      role: "Growth Marketing Lead",
      location: "Lagos, Nigeria (Hybrid)",
      availability: "Consulting Available",
      image: "/assets/images/photo_placeholder.png",
      verified: true,
    },
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4",
    videoPoster: "",
    likes: 240,
    shares: 82,
    views: 1850,
    ctaCount: 64,
    isLiked: false,
    duration: "0:55",
  },
];

export const INITIAL_USER_ACTIVE_PITCHES = [
  {
    id: "user-active-1",
    type: "Personal Intro",
    typeBadge: "INTRO",
    industry: "UIUX Design",
    publishedTime: "Published today",
    expiresIn: "Expires in 24h 0m",
    headline: "Senior UIUX Design/Product Design",
    audience: "Recruiters + Hiring Managers",
    cta: "Hire Me",
    views: 1,
    likes: 0,
    ctaCount: 0,
    duration: "0:40",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    creator: {
      name: "Prisca Osakwe",
      role: "UI/UX Designer",
      location: "Lagos, Nigeria (Remote)",
      availability: "Available Immediately",
      image: "/assets/images/prisca.png",
      verified: true,
    },
    skills: ["UI/UX Design", "Figma", "UX Research", "UI Design"],
    description: "I help fast-growing startups transform complex products into engaging interfaces.",
  },
];

export const INITIAL_DRAFTS = [
  {
    id: "draft-sample-1",
    type: "Personal Intro",
    typeBadge: "INTRO",
    industry: "UIUX Design",
    editedTime: "Edited 2hours ago.",
    headline: "Senior UIUX Design/Product Design",
    progressPercent: 75,
    duration: "0:10",
    category: "Design",
    skills: ["UI/UX Design", "Figma", "UX Research"],
    step: 3,
    description: "I design functional app and websites",
    ctaType: "Hire Me",
  },
];

export const CATEGORIES = [
  { id: "For You", label: "For You", icon: Sparkles },
  { id: "Talents", label: "Talents", icon: Users },
  { id: "Hiring", label: "Hiring", icon: Briefcase },
  { id: "Services", label: "Services", icon: Settings },
  { id: "Companies", label: "Companies", icon: Building },
  { id: "Opportunity", label: "Opportunity", icon: Zap },
];

export const formatTime = (secs) => {
  if (!secs || isNaN(secs)) return "0:00";
  const minutes = Math.floor(secs / 60);
  const seconds = Math.floor(secs % 60);
  return `${minutes}:${seconds < 10 ? `0${seconds}` : seconds}`;
};
